# Generated by Django 4.0.6 on 2022-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='commerce/listings/'),
        ),
    ]
