# Generated by Django 4.0.6 on 2022-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='commerce/listings/'),
            preserve_default=False,
        ),
    ]
