# Generated by Django 4.0.6 on 2022-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(),
        ),
    ]
