# Generated by Django 4.0.6 on 2022-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networker',
            name='image',
            field=models.ImageField(default='network/default.png', upload_to='network/'),
        ),
    ]
