# Generated by Django 4.0.6 on 2022-08-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkpost',
            name='author',
        ),
        migrations.AddField(
            model_name='networkpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='network.networkuser'),
            preserve_default=False,
        ),
    ]
