# Generated by Django 4.0.6 on 2022-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkpost',
            name='edited',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
