# Generated by Django 4.0.6 on 2022-08-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_networkpost_author_networkpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkpost',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='networkuser',
            name='follows',
            field=models.ManyToManyField(related_name='followers', to='network.networkuser'),
        ),
    ]
