# Generated by Django 4.0.6 on 2022-08-17 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0003_alter_networkpost_options_networkuser_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkUser',
            new_name='Networker',
        ),
        migrations.RenameField(
            model_name='networkpost',
            old_name='author',
            new_name='networker',
        ),
    ]
