# Generated by Django 4.0.6 on 2022-08-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_networkuser_networker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkpost',
            name='likes',
        ),
    ]
