# Generated by Django 4.0.6 on 2022-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_networkpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkpost',
            name='likes',
            field=models.ManyToManyField(to='network.networker'),
        ),
    ]
