# Generated by Django 4.0.6 on 2022-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='desktop',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='mobile',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
    ]
